## SERVERS
alias truba='ssh apps@truba.interaktivni-studio.com'
alias deghq='ssh apps@deghq.com'
alias drombulja='ssh root@drombulja.interaktivni-studio.com'

## SYSTEM STUFF
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias ae='vim ~/.bash_aliases' #alias edit
alias ar='. ~/.bash_aliases' #alias reload
alias b='cd -'
alias fp='ps aux | grep '

# mysql connect
alias mysql='/usr/local/bin/mysql -uroot -p'

## WORK FOLDER STUFF
alias home='cd ~/'
alias work='cd ~/work/'
alias moje='cd ~/personal/'
alias yapp='cd ~/work/yapp/'
alias www='cd ~/work/public_html/'
alias dwp='cd ~/work/dwp/'
alias yfw='cd ~/work/yapp-framework/'
alias yiicore='cd ~/work/yapp-framework/vendor/yiisoft/yii2/'

## Git
alias gs="git status"
alias gc="git commit"

## REGULARS
alias ll='ls -al'
alias flushdns='sudo discoveryutil udnsflushcaches'
alias apconf='sudo open -a $EDITOR /usr/local/etc/httpd/httpd.conf'
alias hosts='sudo open -a $EDITOR /private/etc/hosts'
alias vhosts='sudo open -a $EDITOR //usr/local/etc/httpd/extra/httpd-vhosts.conf'
alias phpini='sudo open -a $EDITOR /usr/local/etc/php/7.1/php.ini'
alias erlog='sublime /Users/$USER/work/logs/httpd/error_log'
alias apacherestart='sudo httpd -e info -k restart'
alias memcached-start='memcached -I2m -d start'
alias mariastart='brew services start mysql'
alias mariastop='brew services stop mysql'
alias apache-logs='cd /usr/local/var/log/httpd'
alias codecept='php ~/work/testing-toolkit/vendor/codeception/codeception/codecept'

## OPEN FILE WITH TEXTWRANGLER
function textWranglerOpen() {
	open -a TextWrangler $1
}
alias edit=textWranglerOpen

## Misc
goodMorningClosure() {
	say "Good morning motherfucker!"
	open -a "Google Chrome" https://mail.google.com/ https://github.com
	open -a "Slack"
	say "Updating repositories"
	sh ~/work/pull_repos.sh
	say "All repositories updated";
	say "Updating composer"
	composer self-update
	say "Composer updated"
	say 'Updating brew';
	brew update
	say "Brew updated"
}
alias dobrojutro=goodMorningClosure